### ISSUE TITLE
Add `Stack` component.

### ISSUE THREAD

**Issue by Achintha444** [wso2/oxygen-ui#143]
**The requested Feature**
Add a new component named `Stack` which is a wrapper around the [MUI Stack](https://mui.com/material-ui/react-stack/) component.

**Comment by brionmario** [comment]
@savindi7 Shall we move this to the umbrella issue?

**Comment by brionmario** [comment]
Moved here https://github.com/wso2/oxygen-ui/issues/2.

Hence closing...FYI @Achintha444
