### ISSUE TITLE
Autocomplete has a default padding & a fixed tag size that's inter-fearing when used in external projects

### ISSUE THREAD

**Issue by brionmario** [wso2/oxygen-ui#191]
**Describe the issue:**

**Padding**

```
.oxygen-autocomplete {
    padding-top: 14px;
    padding-bottom: 14px;
}
```

<img width="780" alt="Screenshot 2023-11-19 at 11 53 25" src="https://github.com/wso2/oxygen-ui/assets/25959096/8ecb920d-d477-4ae5-a613-8c5488d2fb2a">

**Tag Size**

```
.oxygen-autocomplete .MuiButtonBase-root {
    height: 32px;
}
```

**How to reproduce:**

Use `Autocomplete` component in a project.

**Expected behavior:**

There shouldn't be any default styling.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Affected Package: @oxygen-ui/react
 - Library Version: 1.5.0
 - OS: Mac
 - Browser: Google Chrome

**Comment by Achintha444** [comment]
This issue is fixed now.
