### ISSUE TITLE
Update the design of the `Chip` component

### ISSUE THREAD

**Issue by Achintha444** [wso2/oxygen-ui#221]
**Is your suggestion related to an experience ? Please describe.**
Update the design of the `Chip` component.

**Describe the solution you would prefer**
Suggested design:
![image](https://github.com/user-attachments/assets/ca9406b4-26ba-4dac-9763-aec23843289b)

**Additional context**
N/A

**Comment by savindi7** [comment]
Let's follow the guidelines for the issue https://github.com/wso2/oxygen-ui/blob/main/CONTRIBUTING.md#creating-an-issue

**Comment by Achintha444** [comment]
> Let's follow the guidelines for the issue https://github.com/wso2/oxygen-ui/blob/main/CONTRIBUTING.md#creating-an-issue

Updated the issue.

**Comment by Achintha444** [comment]
### The design of the chips were changed into following

Since the colours of the chips were not visible enough when placed on the Asgardeo console, the chips designed were changed to the following,

![image](https://github.com/user-attachments/assets/029500b2-367d-4e4b-ba85-8c99889989b9)

**Comment by Achintha444** [comment]
Had a chat with @jeradrutnam and finalised the design as the following,

<img width="434" alt="Screenshot 2024-07-16 at 10 21 19" src="https://github.com/user-attachments/assets/ad72916b-99a8-478a-8b8e-8a85aa87fc9d">
